name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Test
      run: |
        # Install dependencies
        npm ci

        # Build your website here (e.g., compiling SCSS to CSS, minifying assets, etc.)
        # Replace the build commands with your actual build steps
        # Example commands:
        # npm run build:css
        # npm run build:html

        # Validate HTML
        npm run validate:html

        # Lint CSS
        npm run lint:css

        # Add additional tests or checks as needed
